### ISSUE TITLE
Stream Assistant Responses

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/webmaster-23-24#51]
### Why

It'll feel a lot more responsive.

### The Plan

```[tasklist]
#### Tasks
- [ ] Teach myself the streaming API.
- [ ] Figure out how to use websockets without using up all of my Deno Deploy credits.
- [ ] "Proxy" the streaming API over websockets using a REST API.
```

**Comment by lishaduck** [comment]
Note: this should also make the chatbot use partials, if possible.
